# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.203

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests
      run: dotnet test Tests/EerieLeap.Tests.Unit/EerieLeap.Tests.Unit.csproj --no-build --verbosity normal

    - name: Run Functional Tests
      run: dotnet test Tests/EerieLeap.Tests.Functional/EerieLeap.Tests.Functional.csproj --no-build --verbosity normal
      env:
        ASPNETCORE_ENVIRONMENT: Development
        DOTNET_ENVIRONMENT: Development
